de:
  code: de
  currency: EUR
  faker_locale: de_DE
  vat_rate: 0.19
  fx_rate_from_eur: 1.00
  shipping_cost: 4.90
  demand_weight: 1.00
  timezone: Europe/Berlin
  order_hour_weights: [0, 0, 0, 0, 0.05, 0.10, 0.25, 0.55, 0.90, 1.10, 1.20, 1.25, 1.30, 1.35, 1.45, 1.70, 2.10, 2.55, 3.00, 3.20, 2.80, 1.85, 0.90, 0.30]
at:
  code: at
  currency: EUR
  faker_locale: de_AT
  vat_rate: 0.20
  fx_rate_from_eur: 1.00
  shipping_cost: 5.90
  demand_weight: 0.18
  timezone: Europe/Vienna
  order_hour_weights: [0, 0, 0, 0, 0.05, 0.10, 0.25, 0.55, 0.90, 1.10, 1.20, 1.25, 1.30, 1.35, 1.45, 1.70, 2.10, 2.55, 3.00, 3.20, 2.80, 1.85, 0.90, 0.30]
ch:
  code: ch
  currency: CHF
  faker_locale: de_CH
  vat_rate: 0.081
  fx_rate_from_eur: 0.95
  shipping_cost: 9.90
  demand_weight: 0.16
  timezone: Europe/Zurich
  order_hour_weights: [0, 0, 0, 0, 0.05, 0.10, 0.25, 0.55, 0.90, 1.10, 1.20, 1.25, 1.30, 1.35, 1.45, 1.70, 2.10, 2.55, 3.00, 3.20, 2.80, 1.85, 0.90, 0.30]
fr:
  code: fr
  currency: EUR
  faker_locale: fr_FR
  vat_rate: 0.20
  fx_rate_from_eur: 1.00
  shipping_cost: 5.90
  demand_weight: 0.75
  timezone: Europe/Paris
  order_hour_weights: [0, 0, 0, 0, 0.05, 0.10, 0.25, 0.55, 0.90, 1.10, 1.20, 1.25, 1.30, 1.35, 1.45, 1.70, 2.10, 2.55, 3.00, 3.20, 2.80, 1.85, 0.90, 0.30]
be:
  code: be
  currency: EUR
  faker_locale: fr_BE
  vat_rate: 0.21
  fx_rate_from_eur: 1.00
  shipping_cost: 5.90
  demand_weight: 0.14
  timezone: Europe/Brussels
  order_hour_weights: [0, 0, 0, 0, 0.05, 0.10, 0.25, 0.55, 0.90, 1.10, 1.20, 1.25, 1.30, 1.35, 1.45, 1.70, 2.10, 2.55, 3.00, 3.20, 2.80, 1.85, 0.90, 0.30]
es:
  code: es
  currency: EUR
  faker_locale: es_ES
  vat_rate: 0.21
  fx_rate_from_eur: 1.00
  shipping_cost: 6.90
  demand_weight: 0.42
  timezone: Europe/Madrid
  order_hour_weights: [0, 0, 0, 0, 0.05, 0.10, 0.25, 0.55, 0.90, 1.10, 1.20, 1.25, 1.30, 1.35, 1.45, 1.70, 2.10, 2.55, 3.00, 3.20, 2.80, 1.85, 0.90, 0.30]
it:
  code: it
  currency: EUR
  faker_locale: it_IT
  vat_rate: 0.22
  fx_rate_from_eur: 1.00
  shipping_cost: 6.90
  demand_weight: 0.48
  timezone: Europe/Rome
  order_hour_weights: [0, 0, 0, 0, 0.05, 0.10, 0.25, 0.55, 0.90, 1.10, 1.20, 1.25, 1.30, 1.35, 1.45, 1.70, 2.10, 2.55, 3.00, 3.20, 2.80, 1.85, 0.90, 0.30]
nl:
  code: nl
  currency: EUR
  faker_locale: nl_NL
  vat_rate: 0.21
  fx_rate_from_eur: 1.00
  shipping_cost: 5.90
  demand_weight: 0.24
  timezone: Europe/Amsterdam
  order_hour_weights: [0, 0, 0, 0, 0.05, 0.10, 0.25, 0.55, 0.90, 1.10, 1.20, 1.25, 1.30, 1.35, 1.45, 1.70, 2.10, 2.55, 3.00, 3.20, 2.80, 1.85, 0.90, 0.30]
uk:
  code: uk
  currency: GBP
  faker_locale: en_GB
  vat_rate: 0.20
  fx_rate_from_eur: 0.86
  shipping_cost: 5.99
  demand_weight: 0.68
  timezone: Europe/London
  order_hour_weights: [0, 0, 0, 0, 0.05, 0.10, 0.25, 0.55, 0.90, 1.10, 1.20, 1.25, 1.30, 1.35, 1.45, 1.70, 2.10, 2.55, 3.00, 3.20, 2.80, 1.85, 0.90, 0.30]
